export default {
  IDEAS_QUERY_RPC_CLIENT: Symbol(),
  ADMIN_QUERY_RPC_CLIENT: Symbol(),

  IDEAS_COMMAND_RPC_CLIENT: Symbol(),
  USERS_COMMAND_RPC_CLIENT: Symbol(),
  AUTH_COMMAND_RPC_CLIENT: Symbol(),
  NOTIFICATIONS_COMMAND_RPC_CLIENT: Symbol(),
};
