@username = flo
@endpoint = user
@newEmail = jenaxi3316@6mails.com
@deletionToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwTFVKU3RWdVoiLCJpYXQiOjE1OTI5MTkwODcsImV4cCI6MTU5Mjk0Nzg4N30.N-HKGdapuYAl6MUPTkcun92T7c0vZ222OdmiRa8BudE
@changeEmailToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwTFVKU3RWdVoiLCJuZXdFbWFpbCI6ImplbmF4aTMzMTZANm1haWxzLmNvbSIsImlhdCI6MTU5MjkxOTAxOCwiZXhwIjoxNTkyOTI2MjE4fQ.LUnFoQlHy4JFRkIUAAeexhSjMoEoxDxJfKrbo9fI8T8

###

PUT {{apiUrl}}/{{endpoint}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"username":"{{username}}"}

###

POST {{apiUrl}}/{{endpoint}}/requestDeletion
Authorization: Bearer {{userId}}

###

DELETE {{apiUrl}}/{{endpoint}}
Authorization: Bearer {{userId}}
content-type: application/json

{"token":"{{deletionToken}}"}

###

POST {{apiUrl}}/{{endpoint}}/email/requestChange
content-type: application/json
Authorization: Bearer {{userId}}

{"email":"{{newEmail}}"}

###

PUT {{apiUrl}}/{{endpoint}}/email
content-type: application/json

{"token":"{{changeEmailToken}}"}