@username = flo
@endpoint = user
@newEmail = jenaxi3316@6mails.com
@deletionToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYjY2LU1EalUiLCJpYXQiOjE1OTI5MzE0MjgsImV4cCI6MTU5Mjk2MDIyOH0.QbhRZutvi_8U-Eb1T0RpPAaKvjI4G1DcIkU1k8yi6qw
@changeEmailToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwTFVKU3RWdVoiLCJuZXdFbWFpbCI6ImplbmF4aTMzMTZANm1haWxzLmNvbSIsImlhdCI6MTU5MjkxOTAxOCwiZXhwIjoxNTkyOTI2MjE4fQ.LUnFoQlHy4JFRkIUAAeexhSjMoEoxDxJfKrbo9fI8T8

###

PUT {{apiUrl}}/{{endpoint}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"username":"{{username}}"}

###

POST {{apiUrl}}/{{endpoint}}/requestDeletion
Authorization: Bearer {{userId}}

###

DELETE {{apiUrl}}/{{endpoint}}
Authorization: Bearer {{userId}}
content-type: application/json

{"token":"{{deletionToken}}"}

###

POST {{apiUrl}}/{{endpoint}}/email/requestChange
content-type: application/json
Authorization: Bearer {{userId}}

{"email":"{{newEmail}}"}

###

PUT {{apiUrl}}/{{endpoint}}/email
content-type: application/json

{"token":"{{changeEmailToken}}"}