@endpoint=auth

# TODO would be better to put those variables in a file, which is not committed
@sessionId = XXX
@email = XXX
@emailSignInToken = XXX
@googleSignInCode = XXX

###

POST {{apiUrl}}/{{endpoint}}/signin/email
content-type: application/json

{"email":"{{email}}"}

###

POST {{apiUrl}}/{{endpoint}}/signin/email/confirm
content-type: application/json

{"token":"{{emailSignInToken}}"}

###

GET {{apiUrl}}/{{endpoint}}/signin/google/url

###

POST {{apiUrl}}/{{endpoint}}/signin/google
content-type: application/json

{"code":"{{googleSignInCode}}"}

###

POST {{apiUrl}}/{{endpoint}}/refresh

###

POST {{apiUrl}}/{{endpoint}}/signout

###

POST {{apiUrl}}/{{endpoint}}/revoke
content-type: application/json

{"sessionId":"{{sessionId}}"}