@sessionId = ___
@email = denona4363@kartk5.com
@emailSignInToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIyZDVjN2QwOC1mNDBjLTQ2MzgtODUzOS1kMTIyNjRjMzM5ZjIiLCJlbWFpbCI6ImRlbm9uYTQzNjNAa2FydGs1LmNvbSIsImlhdCI6MTU5Mzc4NjgyMywiZXhwIjoxNTkzNzk0MDIzfQ.P6UBYGHi0CQt335nu4xcTiAZDCu-kvF9_7G7poc-NJI
@googleSignInCode = 4/1QHEYTZgTLdqLFwWDWs9puxiNYP0StyxTDlfOf-yt1UiGg8xzvcLESzGfQ3c95f5_lVPO386QnO-lZUJQcOVmKg

###

POST {{apiUrl}}/auth/signin/email
content-type: application/json

{"email":"{{email}}"}

###

POST {{apiUrl}}/auth/signin/email/confirm
content-type: application/json

{"token":"{{emailSignInToken}}"}

###

GET {{apiUrl}}/auth/signin/google/url

###

POST {{apiUrl}}/auth/signin/google
content-type: application/json

{"code":"{{googleSignInCode}}"}

###

POST {{apiUrl}}/auth/refresh

###

POST {{apiUrl}}/auth/signout

###

POST {{apiUrl}}/auth/revoke
content-type: application/json

{"sessionId":"{{sessionId}}"}