@sessionId = ___
@email = diravi5860@wwmails.com
@emailSignInToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIxYzE5NTEyZi01OGIxLTRmMDQtOTQxNC1lMTgwMWRkYzQyODUiLCJlbWFpbCI6ImRpcmF2aTU4NjBAd3dtYWlscy5jb20iLCJpYXQiOjE1OTM5NzQ2NjgsImV4cCI6MTU5Mzk4MTg2OH0.28w9NT4ESNG5c938DqFBJOZbgeJiFqK7S2DRB9Fm61g
@googleSignInCode = 4/1gHpkXfa72rVhgXk14I7NR6wawjMlhmm1SoB5PTCpWQ3XQVpzMiRzwi0oihs6sXFkr8_W938XMiWQkatwoZv_Oo

###

POST {{apiUrl}}/auth/signin/email
content-type: application/json

{"email":"{{email}}"}

###

POST {{apiUrl}}/auth/signin/email/confirm
content-type: application/json

{"token":"{{emailSignInToken}}"}

###

GET {{apiUrl}}/auth/signin/google/url

###

POST {{apiUrl}}/auth/signin/google
content-type: application/json

{"code":"{{googleSignInCode}}"}

###

POST {{apiUrl}}/auth/refresh

###

POST {{apiUrl}}/auth/signout

###

POST {{apiUrl}}/auth/revoke
content-type: application/json

{"sessionId":"{{sessionId}}"}