@endpoint = user
@id = ul4Zs3mVo

###

GET {{apiUrl}}/{{endpoint}}/me
Authorization: Bearer {{userId}}

###

GET {{apiUrl}}/{{endpoint}}

###

GET {{apiUrl}}/{{endpoint}}/{{id}}

###

GET {{apiUrl}}/personalData
Authorization: Bearer {{userId}}