package(default_visibility = ["//visibility:public"])

exports_files([
    "kafka.yaml",
    "zookeeper.yaml",
    "gcp/database-storage.yaml",
    "gcp/config.yaml",
    "gcp/ingress.yaml",
    "gcp/tls-secret.yaml",
])