package(default_visibility = ["//visibility:public"])

exports_files([
    "kafka.yaml",
    "zookeeper.yaml",
    "database-storage.yaml",
    "config.yaml",
    "ingress.yaml",
    "tls-secret.yaml",
])