import { Environments } from '@centsideas/enums';
import { IEnvironment } from './environment.model';

export const defaultDevEnv: IEnvironment = {
  environment: Environments.Dev,
  refreshTokenSecret: '',
  accessTokenSecret: '',
  loginTokenSecret: '',
  changeEmailTokenSecret: '',
  frontendServerExchangeSecret: '',
  sendgridApiKey: '',
  googleClientId: '',
  googleClientSecret: '',
  vapidPublicKey: '',
  vapidPrivateKey: '',

  gatewayUrl: 'http://localhost:3000',
  ideasRpcPort: 40000,
  ideasRpcHost: 'ideas',
  mainClientUrl: 'http://localhost:4200',
  adminClientUrl: 'http://localhost:8080',
  adminSocketUrl: 'http://localhost:3001',
  ideasHost: 'ideas:3000',
  consumerHost: 'consumer:3000',
  reviewsHost: 'reviews:3000',
  usersHost: 'users:3000',
  notificationsHost: 'notifications:3000',
  adminHost: 'admin:3000',
  ideasDatabaseUrl: 'mongodb://ideas-event-store:27017',
  reviewsDatabaseUrl: 'mongodb://reviews-event-store:27017',
  projectionDatabaseUrl: 'mongodb://projection-database:27017',
  usersDatabaseUrl: 'mongodb://users-event-store:27017',
  notificationsDatabaseUrl: 'mongodb://notifications-event-store:27017',
  adminDatabaseUrl: 'mongodb://admin-database:27017',
  kafkaAdvertisedHostName: 'kafka',
  kafkaZookeeperConnect: 'zookeeper:2181',
  kafkaAdvertisedPort: 9092,
  kafkaBrokerHost: 'kafka:9092',
};
