@ideaId = ueouRZvmF
@reviewId = {{create.response.body.id}}

###

# @name create
POST {{apiUrl}}/review
content-type: application/json
Authorization: Bearer {{userId}}

{"ideaId":"{{ideaId}}"}

###

PUT {{apiUrl}}/review/{{reviewId}}/content
content-type: application/json
Authorization: Bearer {{userId}}

{"content":"This idea is awesome!"}

###

PUT {{apiUrl}}/review/{{reviewId}}/score
content-type: application/json
Authorization: Bearer {{userId}}

{
  "control": 5,
  "entry": 4,
  "need": 3,
  "time": 2,
  "scale": 1
}

###

PUT {{apiUrl}}/review/{{reviewId}}/publish
Authorization: Bearer {{userId}}

### TODO get events in .rest files