@ideaId = {{create.response.body.id}}

###

# @name create
POST {{apiUrl}}/idea
Authorization: Bearer {{userId}}

###

PUT {{apiUrl}}/idea/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":" "}

###

PUT {{apiUrl}}/idea/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":"no"}

###

PUT {{apiUrl}}/idea/{{ideaId}}/description
content-type: application/json
Authorization: Bearer {{userId}}

{"description":"Not really describing the idea. puste"}

###

PUT {{apiUrl}}/idea/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["powerful", "awesome","cool", "kuchen"]}

###

PUT {{apiUrl}}/idea/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["awesome","cool","best"]}

###

PUT {{apiUrl}}/idea/{{ideaId}}/publish
Authorization: Bearer {{userId}}

###

DELETE {{apiUrl}}/idea/{{ideaId}}
Authorization: Bearer {{userId}}
