@ideaId = {{create.response.body.id}}
@endpoint = idea

###

# @name create
POST {{apiUrl}}/{{endpoint}}
Authorization: Bearer {{userId}}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":"The best idea ever"}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":"no"}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/description
content-type: application/json
Authorization: Bearer {{userId}}

{"description":"Not really describing the idea."}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["powerful", "awesome","cool"]}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["awesome","cool","best"]}

###

PUT {{apiUrl}}/{{endpoint}}/{{ideaId}}/publish
Authorization: Bearer {{userId}}

###

DELETE {{apiUrl}}/{{endpoint}}/{{ideaId}}
Authorization: Bearer {{userId}}
