@ideaId = {{create.response.body.id}}

###

# @name create
POST {{apiUrl}}/idea
Authorization: Bearer {{userId}}

###

PUT {{apiUrl}}/idea/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":"Marketplace for 3D Models and similar assets"}

###

PUT {{apiUrl}}/idea/{{ideaId}}/rename
content-type: application/json
Authorization: Bearer {{userId}}

{"title":"no"}

###

PUT {{apiUrl}}/idea/{{ideaId}}/description
content-type: application/json
Authorization: Bearer {{userId}}

{"description":"A platform where people cann sell and buy 3d models"}

###

PUT {{apiUrl}}/idea/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["3d","marketplace","ecommerce"]}

###

PUT {{apiUrl}}/idea/{{ideaId}}/tags
content-type: application/json
Authorization: Bearer {{userId}}

{"tags": ["awesome","cool","best"]}

###

PUT {{apiUrl}}/idea/{{ideaId}}/publish
Authorization: Bearer {{userId}}

###

DELETE {{apiUrl}}/idea/{{ideaId}}
Authorization: Bearer {{userId}}
